model_params:
  architecture: 'fixMatch'
  pretrained_weights: 'convnextv2_atto.fcmae'  # choose from timm models
  supervised_criterion: 'MSE'
  in_channels: 8
  nbr_outputs: 1
  drop_rate: 0.4

data_params:
  data_path: "/home/pop-dens/data/So2Sat_POP_Part1"
  train_batch_size: 128
  #val_batch_size:  1024
  num_workers: 28

train_params:
  LR: 0.00001
  max_epochs: 1
  L2_reg: 0.005
  beta1: 0.9
  beta2: 0.999
  ema_alpha: 0.99
  use_teacher: False
  seed: 42

hparam_search:
  active: False
  hparam_name: 'LR'
  lowest: 0.000001
  highest: 0.001
  nbr_values: 10  # Evaluates this many values by splitting the range into equal parts
  nbr_batches: 10 # Number of batches after which the evaluation is done

save_dirs:
  log_save_dir: "/home/sameberl/logs/"
  model_save_dir: "/home/sameberl/models"

student_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5

teacher_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5
