info:
  info: 'bigger network + 15 channels (7spring, 3winter, 4lu, 1lcz, 1dem)'

model_params:
  architecture: 'fixMatch'
  pretrained_weights: 'convnextv2_nano.fcmae'  # choose from timm models
  supervised_criterion: 'LinUncertainty'
  unsupervised_criterion: 'contrastive'
  unsupervised_factor: 10000
  retrain: False
  retrain_from: 'convnextv2_nano.fcmae_2023_10_08-17_25_51.pt'
  in_channels: 15
  nbr_outputs: 1
  drop_rate: 0.1
  #  drop_rate_teacher: 0.4

data_params:
  data_path: "/home/pop-dens/data/So2Sat_POP_Part1"
  train_batch_size: 256
  num_workers: 32
  drop_labels: False
  percentage_unlabeled: 0.0

train_params:
  LR: 0.00005
  max_epochs: 140
  L2_reg: 0.005
  beta1: 0.9
  beta2: 0.999
  ema_alpha: 0.95
  use_teacher: False
  seed: 42
  num_samples_teacher: 100

hparam_search:
  active: False
  hparam_name: 'LR'
  lowest: 0.0000001
  highest: 0.01
  nbr_values: 5  # Evaluates this many values by splitting the range into equal parts
  nbr_batches: 5 # Number of batches after which the evaluation is done

save_dirs:
  log_save_dir: "/home/sameberl/logs/"
  model_save_dir: "/home/sameberl/models"

student_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5
#  - GaussNoise:
#      #var_limit: (10.0, 50.0)
#      mean: 0
#      per_channel: True
#      always_apply: False
#      p: 1
#  - Normalize:
#      # mean: (0.485, 0.456, 0.406)
#      # std: (0.229, 0.224, 0.225)
#      max_pixel_value: 1.0
#      always_apply: True
#      # p: 1.0

teacher_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5
