info:
  info: 'Without pretraining'

model_params:
  architecture: 'fixMatch'
  pretrained_weights: 'convnextv2_atto.fcmae'  # choose from timm models
  pretrained: True
  supervised_criterion: 'MSE'
  unsupervised_criterion: 'triplet'
  unsupervised_factor: 1_000_000
  retrain: True
  retrain_from: 'convnextv2_atto.fcmae-2024_01_31-16_56_34.pt'
  in_channels: 9
  nbr_outputs: 1
  drop_rate: 0.2
  #  drop_rate_teacher: 0.4

data_params:
  data_dir: "/home/pop-dens/data/So2Sat_POP_Part1"
  train_batch_size: 32
  val_batch_size: 32
  num_workers: 32
  reduce_zeros: False
  reduce_zeros_percent: 0.5
  reduce_data: False
  reduce_data_percent: 0.9
  unlabeled_data: True
  reduce_supervised: False
  reduce_supervised_percent: 0.8
  seed: 42
  use_spring_rgb: True
  use_lu: True
  use_lcz: True
  use_dem: True
  use_viirs: False

train_params:
  LR: 0.0001
  max_epochs: 1
  L2_reg: 0.005
  beta1: 0.9
  beta2: 0.999
  ema_alpha: 0.95
  seed: 42
  num_samples_teacher: 30

save_dirs:
  log_save_dir: "/home/sameberl/logs/"
  model_save_dir: "/home/sameberl/models"

transform_params:
  apply_rot_and_flip: True
  apply_noise: True
  noise_mean: 0
  noise_std_min: 0.01
  noise_std_max: 0.07
  noise_p: 0.5
  apply_brightness: True
  brightness_range:
    - 0.8
    - 1.2
  brightness_p: 0.5
  apply_contrast: True
  contrast_range:
    - 0.8
    - 1.2
  contrast_p: 0.5


