model_params:
  architecture: 'fixMatch'
  pretrained_weights: 'convnextv2_atto.fcmae'  # choose from timm models
  supervised_criterion: 'LinUncertainty'
  retrain: False
#  retrain_from: 'convnextv2_atto.fcmae_2023_10_14-13_56_54.pt'
#  retrain_from: 'convnextv2_atto.fcmae_2023_10_16-18_47_24.pt'
  retrain_from: 'convnextv2_atto.fcmae_2023_10_18-18_43_52.pt'
  in_channels: 7
  nbr_outputs: 1
  drop_rate: 0.3
#  drop_rate_teacher: 0.4

data_params:
  data_path: "/home/sam/Desktop/so2sat_test/tmp_train"
  train_batch_size: 32
  #val_batch_size:  1024
  num_workers: 6
  semi_supervised: True
  percentage_unlabeled: 0.5

train_params:
  LR: 0.00001
  max_epochs: 5
  L2_reg: 0.005
  beta1: 0.9
  beta2: 0.999
  ema_alpha: 0.95
  use_teacher: True
  seed: 42
  num_samples_teacher: 80

hparam_search:
  active: False
  hparam_name: 'LR'
  lowest: 0.0000001
  highest: 0.01
  nbr_values: 5  # Evaluates this many values by splitting the range into equal parts
  nbr_batches: 5 # Number of batches after which the evaluation is done

save_dirs:
  log_save_dir: "/home/sam/Desktop/logs/"
  model_save_dir: "/home/sam/Desktop/logs/models/"

student_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5

teacher_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5
