info:
  info: 'No Teacher with 80% unlabeled (should be same as drop_data: True) | Sigmoid * 54k'

model_params:
  architecture: 'fixMatch'
  pretrained_weights: 'convnextv2_atto.fcmae'  # choose from timm models
  pretrained: True
  supervised_criterion: 'MSE'
  unsupervised_criterion: 'triplet'
  unsupervised_factor: 1_000_000
  retrain: False
  retrain_from: 'convnextv2_nano.fcmae_2023_10_08-17_25_51.pt'
  in_channels: 3
  nbr_outputs: 1
  drop_rate: 0.2
  #  drop_rate_teacher: 0.4

data_params:
  data_path: "/home/pop-dens/data/So2Sat_POP_Part1"
  train_batch_size: 32
  num_workers: 32
  drop_labels: True
  percentage_unlabeled: 0.8
  drop_data: False  # Drops 80% of the training data

train_params:
  LR: 0.0001
  max_epochs: 50
  L2_reg: 0.005
  beta1: 0.9
  beta2: 0.999
  ema_alpha: 0.95
  use_teacher: False
  seed: 42
  num_samples_teacher: 30

save_dirs:
  log_save_dir: "/home/sameberl/logs/"
  model_save_dir: "/home/sameberl/models"

student_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5
#  - GaussNoise:
#      #var_limit: (10.0, 50.0)
#      mean: 0
#      per_channel: True
#      always_apply: False
#      p: 1
#  - Normalize:
#      # mean: (0.485, 0.456, 0.406)
#      # std: (0.229, 0.224, 0.225)
#      max_pixel_value: 1.0
#      always_apply: True
#      # p: 1.0

teacher_transforms:
  - HorizontalFlip:
      p: 0.5
  - VerticalFlip:
      p: 0.5
  - RandomRotate90:
      p: 0.5
